accounts/urls.py
from distutils.log import Log
from django.urls import path
from django.contrib.auth.views import LoginView,LogoutView
from . import views

app_name='accounts'

urlpatterns=[
    path('login/',LoginView.as_view(),name='login'),
    path('logout/',LogoutView.as_view(),name='logout'),
    path('signup/',views.SignupView.as_view(),name='signup'),
    
]

app/urls.py
from django.urls import path
from . import views
app_name='app'
urlpatterns=[
    path('',views.HelloClass.as_view(),name='index'),
    path('list/',views.AppList.as_view(),name='app-list'),
    path('detail/<int:pk>/',views.AppDetail.as_view(),name='app-detail'),
    path('create/',views.AppCreate.as_view(),name='app-create'),
    path('delete/<int:pk>',views.AppDelete.as_view(),name='app-delete'),
    path('update/<int:pk>',views.AppUpdate.as_view(),name='app-update'),
    path('comment/create/<int:key>',views.CommentCreate.as_view(),name='comment-create'),
    path('reply/<int:reply_pk>/',views.reply_create,name="reply-create"),
    

    
]

project/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("accounts/",include('accounts.urls')),
    path("",include('app.urls')),
]

accounts/models.py
from django.db import models

# Create your models here.

app/models.py
from django.db import models

class App(models.Model):
    title=models.CharField(max_length=100)
    text=models.TextField()
    degree=models.CharField(
        max_length=100,
        choices=(('0','0%'),('10','10%'),("20","20%"),("30","30%"),
        ("40","40%"),("50","50%"),("60","60%"),("70","70%"),("80","80%"),
        ("90","90%"),("100","100%"),("120","limit-break"),),
        null=True,
    )
    user=models.ForeignKey('auth.User',on_delete=models.CASCADE)

class Comment(models.Model):
    text=models.TextField()
    target=models.ForeignKey('App',on_delete=models.CASCADE,verbose_name='対象記事')
    created_at=models.DateTimeField('CreatedDate',auto_now=True)
    username=models.ForeignKey('auth.User',on_delete=models.CASCADE,verbose_name='ユーザー名')      
    parent=models.ForeignKey('self',verbose_name='parent',null=True,blank=True,on_delete=models.CASCADE)
    def __str__(self):
        return self.text[:20]

    

accounts/forms.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

class SignupForm(UserCreationForm):
    class Meta:
        model=User
        fields=('username',)

app/forms.py
from django import forms
from .models import Comment
class CommentCreateForm(forms.ModelForm):
    text=forms.CharField(
        required=True,
        widget=forms.Textarea(
            attrs={
                'placeholder':'投稿に対してコメントを書いてください',
                'rows':10,
                'class':'mx-auto',
                'style':'width:100%',
            }
        )
    )
    class Meta:
        model=Comment
        exclude=('username','target','created_at','parent')

accounts/views.py
from django.shortcuts import render
from django.contrib.auth.models import User
from django.views.generic import CreateView
from django.urls import reverse_lazy

from .forms import SignupForm


# Create your views here.
class SignupView(CreateView):
    model=User
    template_name='accounts/signup.html'
    form_class=SignupForm
    success_url=reverse_lazy('accounts:login')

app/views.py
from django.shortcuts import render,redirect,get_object_or_404
from django.views.generic import TemplateView,ListView,DetailView,CreateView,DeleteView,UpdateView
from app.forms import CommentCreateForm
from app.models import App, Comment
from django.urls import reverse_lazy
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.exceptions import PermissionDenied

# Create your views here.
class HelloClass(TemplateView):
    template_name='index.html'

class AppList(ListView):
    template_name='app/app_list.html'
    model=App

class AppDetail(LoginRequiredMixin,DetailView):
    template_name='app/app_detail.html'
    model=App

    def get_context_data(self,**kwargs):
        context=super().get_context_data(**kwargs)
        context['parent_list']=self.object.comment_set.filter(parent__isnull=True)
        return context


class AppCreate(LoginRequiredMixin,CreateView):
    template_name='app/app_create.html'
    model=App
    fields=('title','text','degree')
    success_url=reverse_lazy('app:app-list')

    def form_valid(self,form):
        form.instance.user=self.request.user
        return super().form_valid(form)



class AppDelete(LoginRequiredMixin,DeleteView):
    template_name='app/app_delete.html'
    model=App
    success_url=reverse_lazy('app:app-list')

    def get_object(self,queryset=None):
        data=super().get_object(queryset)

        if data.user != self.request.user:
            raise PermissionDenied
        return data


        

class AppUpdate(LoginRequiredMixin,UpdateView):
    template_name='app/app_update.html'
    model=App
    fields=('title','text','degree')
    success_url=reverse_lazy('app:app-list')

    def get_object(self,queryset=None):
        data=super().get_object(queryset)

        if data.user != self.request.user:
            raise PermissionDenied
        return data

class CommentCreate(CreateView):
    template_name='app/comment_create.html'
    model=Comment
    form_class=CommentCreateForm
    def form_valid(self,form):
        post_pk=self.kwargs['key']
        post=get_object_or_404(App,pk=post_pk)
        comment=form.save(commit=False)
        comment.target=post
        comment.username=self.request.user
        comment.save()
        return redirect('app:app-detail',pk=post_pk)
    def get_context_data(self, **kwargs):
        context=super().get_context_data(**kwargs)
        context['app']=get_object_or_404(App,pk=self.kwargs['key'])
        return context

def reply_create(request,reply_pk,):
    comment=get_object_or_404(Comment,pk=reply_pk)
    post=comment.target
    form=CommentCreateForm(request.POST or None)

    if request.method=='POST':
        reply=form.save(commit=False)
        reply.parent=comment
        reply.target=post
        reply.username=request.user
        reply.save()
        return redirect('app:app-detail',pk=post.pk)

    context={
        'form':form,
        'post':post,
        'comment':comment,
    }
    return render(request,'app/reply_create.html',context)

    

accounts/templates/accounts/signup.html
{% extends 'base.html'%}

{%block title%}ユーザー登録{%endblock%}

{%block body%}
<form method="post" >
    {%csrf_token%}
    <div class="form-group">
        <label for="exampleInputEmail1">ユーザーネーム</label>
        <input type="text" name="username" placeholder="username" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp">
    </div>

    <div class="form-group">
      <label for="exampleInputPassword1">パスワード</label>
      <input type="password" name="password1" placeholder="password" class="form-control" id="exampleInputPassword1">
    </div>

    <div class="form-group">
        <label for="exampleInputPassword2">確認用</label>
        <input type="password" name="password2" placeholder="Please enter the same password again" class="form-control" id="exampleInputPassword2">
    </div>

    <!-- name=password1,password2はUserCreationFormのフィールド名に対応している。 -->


    <small>Please enter a password with at least 8 characters</small><br>
    {%if form.errors%}
    登録できませんでした。確認のうえ、再度入力してください。<br>
    {%endif%}
    <br>
    <button type="submit" class="btn btn-outline-primary float-right">アカウント作成</button>
    
</form>


{%endblock%}

app/templates/app/app_create.html
{% extends 'base.html' %}
{% block title %}create{% endblock title %}
{% block body %}
<form method="post">
    {% csrf_token %}
    <div class="card  mt-5" >
        <div class="card-header" style="width:100%">
            {{form.as_p}} 
        </div>
        <button class="btn btn-outline-primary " type="submit">作成</button>          
    </div> 
</form>
{% endblock body %}

app/templates/app/app_delete.html
{% extends 'base.html' %}
{% block title %}delete{% endblock title%}
{% block body %}
<div class="alert alert-info"  role="alert">
    This page is a "delete-only page". You can delete items displayed here.
</div>
<div class="mx-auto"  style="width:90%">
    <form method="POST">{% csrf_token %}
        <div class="card my-3 mx-auto" style="width:80%">
            <div class="card-body">
              <h2 class="card-title">{{object.title}}</h2>
              <h5 class="card-text">{{object.text}}</5>
            </div>
            <ul class="list-group list-group-flush">
              <li class="list-group-item">degree:{{object.degree}}</li>
              <li class="list-group-item">user:ユーザーネーム</li>
              <li class="list-group-item">time:時間</li>
            </ul>
            <button type="submit" class="btn btn-outline-danger">Remove「{{object.title}}」</button>
            
          </div>   
    </form>
</div>



{% endblock body%}

app/templates/app/app_detail.html
{% extends 'base.html' %}
{% block title %}detail{% endblock title %}
{% block body %}
<div class="card my-3 mx-auto" style="width:90%">
    <div class="card-body">
      <h2 class="card-title">{{object.title}}</h2>
      <h5 class="card-text">{{object.text}}</5>
    </div>
    <ul class="list-group list-group-flush">
      <li class="list-group-item">degree:{{object.degree}}</li>
      <li class="list-group-item">user:{{object.user}}</li>
      <li class="list-group-item">time:時間</li>
    </ul> 
    
    <div class="card-body row">
      {% if request.user == object.user%}
        <a href="{% url 'app:app-update' object.pk %}" class="btn btn-outline-primary float-right col-3 mx-auto">更新</a>
        <a href="{% url 'app:app-delete' object.pk %}" class="btn btn-outline-danger float-right col-3 mx-auto">削除</a>
        <a href="{% url 'app:comment-create' object.pk %}" class="btn btn btn-outline-warning float-right col-3 mx-auto">コメント</a>
        <a href="{% url 'app:app-list' %}" class="btn btn-outline-info float-right col-3 mx-auto">一覧</a>
    
      {%else%}
        <a href="{% url 'app:comment-create' object.pk %}" class="btn btn btn-outline-warning float-right mx-auto col-5">comment</a>
        <a href="{% url 'app:app-list' %}" class="btn btn-outline-info float-right col-5 mx-auto">←list</a>       
      {%endif%}

    </div>
</div>

{% for parent in parent_list %}
<div class="mx-auto" style="width:90%">
  <div class="row mx-auto" style="width:100%;"> 
    <a href="{% url 'app:reply-create' parent.pk %}" class="list-group-item list-group-item-action" style="display:block;">
    <div class="d-flex w-100 justify-content-between">
      <h5>{{parent.username}}&emsp;</h5>
      <small class="text-muted">{{ parent.created_at|date:"Y-m-j H:i:s"}}</small>
    </div>
    <p class="text-muted">{{parent.text}}</p>
    <small class="text-muted">返信</small>
    <br>
  </a>
</div>
  {% with reply_list=parent.comment_set.all %}
    {% include 'app/include_reply.html' %}
  {% endwith %}
</div> 
{% endfor %}
{% endblock body %}

app/templates/app/app_list.html
{% extends 'base.html' %}
{% block title %}list{% endblock title %}
{% block body %}
<div class="row mx-auto" style="width:90%">
    {% for i in object_list%}
    <div class="list-group">
    <a href="{% url 'app:app-detail' i.pk %}" class="list-group-item list-group-item-action my-2" style="display:block">
        <div class="d-flex w-100 justify-content-between">
          <h5 class="mb-1">{{i.title}}</h5>
          <small class="text-muted">day~~</small>
        </div>
        <p class="mb-1 text-muted">{{i.text|truncatechars:15}}</p>
        <small class="text-muted">コメント</small>
    </a>
    </div>
    {%endfor%}
</div>

{% endblock body %}
 

app/templates/app/app_update.html
{% extends 'base.html' %}
{% block title %}update{% endblock title %}
{% block body %}
<form method="post">
    {% csrf_token %}
    <div class="card  mt-5" >
        <div class="card-header" style="width:100%">
            {{form.as_p}} 
        </div>
        <button class="btn btn-outline-primary " type="submit">更新</button>          
    </div> 
</form>
{% endblock body %}

app/templates/app/comment_create.html
{% extends 'base.html' %}
{% block title %}commnt{% endblock title%}
{% block body %}
<div class="card  mt-5 mx-auto" style="width:90%">
        <div class="row">
            <div class="card">
                <div class="card-header " >
                    {{app.title}}
                </div>
                <ul class="list-group list-group-flush">
                  <li class="list-group-item" >{{app.text}}</li>
                  <li class="list-group-item" >{{app.user}}</li>
                </ul>
            </div>
        </div> 
</div>

<div class="card  mt-5 mx-auto" style="width:90%">
        <form method="POST" id="comment-form">
          {% csrf_token %} 
            <div class="row">
                <div class="card">
                    <div class="card-header " >
                    </div>
                    <ul class="list-group list-group-flush">
                      <li class="list-group-item" >{{form.text}}</li>
                      <!-- #form.as_p以外にもフォームを表示する方法がある。
                      その一例がform.フィールド名である。
                      これはフィールドを一つずつ表示することができるため見た目を整えやすくなる。 -->
                    </ul>
                    <button type="submit" class="btn btn-outline-warning float-right">comment</button>
                </div>
            </div> 
        </form>
</div>
{% endblock body%}

app/templates/app/include_reply.html
{% for reply in reply_list %}
<div style="width:90%; margin-right:0; margin-left:auto;">
    <a href="#" class="list-group-item list-group-item-action" style="display:block;">
    <div class="d-flex w-100 justify-content-between">
      <h5>{{reply.username}}&emsp;</h5>
      <small class="text-muted">{{ reply.created_at|date:"Y-m-j H:i:s"}}</small>
    </div>
    <p class="text-muted">{{reply.text}}</p>
    <br>
  </a>
</div>
  {% with reply_list=reply.comment_set.all %}
    {% include 'app/include_reply.html' %}
  {% endwith %} 
{% endfor %}

app/templates/app/reply_create.html
{% extends 'base.html' %}

{% block title %}commnt{% endblock title%}
{% block body %}
<h1>To:</h1>
<div class="card-header">
    <ul class="list-group list-group-flush">
        <li class="list-group-item">{{comment.username}}</li>
        <li class="list-group-item">{{comment.text}} </li>  
    </ul>
</div>
<br><br>
<div class="card  mt-5 mx-auto">
        <form method="POST">
          {% csrf_token %}
            <div class="card-header">
                <div class="form-group">
                    <label for="UserNameIDtoFor">UserName</label>
                    <input type="email" class="form-control" id="UserNameIDtoFor"  value="{{user.get_username}}" readonly>
                </div>
                <br>
                {{form.text}}    
            </div> 
        </div>
        <button type="submit" class="btn btn-outline-warning float-right" style="width:100%">リプライ</button>
        </form>
      </div>
</div>


{% endblock body%}

templates/base.html
<!DOCTYPE html>
<html lang="ja">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.0/css/all.min.css" integrity="sha512-xh6O/CkQoPOWDdYTDqeRdPCVd1SpvCA9XXcUnZS2FmJNp1coAFzvtCN9BmamE+4aHK8yyUHUSCcJHgXloTyT2A==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <title>{% block title %}{% endblock title %}</title>
    <meta name="viewport" content="width=device-width, initial-scale=1" />
</head>
<body>
  <div class="row mx-auto" style="width:100%">        
            <nav class="navbar navbar-dark bg-dark">
            {% if request.user.is_authenticated %}
              <a href="{%url 'app:index'%}" class="col-2"><i class="fa-solid fa-house fa-3x" style="color: rgb(0, 191, 255)"></i></a>    
              <a href="{%url 'app:app-list'%}" class="col-2"><i class="fa-solid fa-list fa-3x" style="color: rgb(0, 191, 255)"></i></a>
              <a href="{%url 'app:app-create'%}"class="col-2"><i class="fa-solid fa-plus fa-3x" style="color: rgb(0, 191, 255)"></i></a> 
              <a href="#"class="col-2"><i class="fa-solid fa-user fa-3x" style="color: rgb(0, 191, 255)"></i></a> 
              <a  href="{% url 'accounts:logout'%}"><i class="fa-solid fa-person-walking-arrow-right fa-3x"></i></a>
            {% else %}
              <a  href="{% url 'accounts:login'%}"><i class="fa-solid fa-right-to-bracket fa-3x"></i></a>
              <a  href="{% url 'accounts:signup' %}"><i class="fa-solid fa-user-check fa-3x"></i></a>

            {% endif %} 
            </nav>
  </div>
<div style="margin-bottom:10rem;">
{% block body %}{% endblock body %}
</div>
</body>
</html>

templates/index.html
{%extends 'base.html'%}

{%block title%}
トップぺージ
{%endblock title%}


{% block body%}
<h1>morning!!!</h1> 
{%endblock body %}
    